apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: blockchain-proxycrypto-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: id-blockchain-proxycrypto
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 10