apiVersion: v1
kind: Service
metadata:
  name: id-blockchain-proxycrypto-service
  labels:
    product: identidad    
    tier: proxycrypto
    phase: uat
    deployment: v1
spec:
  selector:
    product: identidad
    app: blockchainproxycrypto
  ports:
   - protocol: TCP
     port: 80
     targetPort: 5000
     name: http
  type: LoadBalancer